CC=g++                                                                          
                                                                                
all: $1                                                              
                                                                                
vector: contest.cpp                                                        
	$(CC) $1.cpp -o contest -std=c++17                                         
                                                                                
